name: docker

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'Directory.*'
      - 'src/**'
      - 'build/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:${{ github.ref_name }},${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:latest
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
