name: docker

on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published]
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'Directory.*'
      - 'src/**'
      - 'build/**'
jobs:  
  docker-build:
    if: github.repository == 'WeihanLi/dotnet-exec'
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push release
      id: docker_build_release
      uses: docker/build-push-action@v5
      if: ${{ github.event_name == 'release' }}
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:${{ github.event.release.tag_name }}

    - name: Build and push web release
      id: docker_build_web_release
      uses: docker/build-push-action@v5
      if: ${{ github.event_name == 'release' }}
      with:
        context: ./
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:${{ github.event.release.tag_name }}-web

    - name: Build and push web
      id: docker_build_web
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile.web
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:web

    - name: Build and push latest
      id: docker_build_latest
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dotnet-exec:latest
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
